import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:handy_connect/core/locator.dart';
import 'package:handy_connect/features/auth/presentation/bloc/auth_bloc.dart';
import 'package:handy_connect/features/customer/presentation/bloc/booking_bloc.dart';
import 'package:handy_connect/features/handyman/domain/models/handyman_user.dart';
import 'package:go_router/go_router.dart';
import 'package:handy_connect/features/handyman/domain/models/service_request.dart';

class BookingFormScreen extends StatelessWidget {
  final HandymanUser handyman;

  const BookingFormScreen({super.key, required this.handyman});

  @override
  Widget build(BuildContext context) {
    return BlocProvider(
      create: (_) => locator<BookingBloc>(),
      child: BookingFormView(handyman: handyman),
    );
  }
}

class BookingFormView extends StatefulWidget {
  final HandymanUser handyman;

  const BookingFormView({super.key, required this.handyman});

  @override
  State<BookingFormView> createState() => _BookingFormViewState();
}

class _BookingFormViewState extends State<BookingFormView> {
  final _formKey = GlobalKey<FormState>();
  final _issueController = TextEditingController();
  DateTime? _preferredDateTime;

  Future<void> _selectDateTime(BuildContext context) async {
    final date = await showDatePicker(
      context: context,
      initialDate: DateTime.now(),
      firstDate: DateTime.now(),
      lastDate: DateTime.now().add(const Duration(days: 365)),
    );
    if (date == null) return;

    final time = await showTimePicker(
      context: context,
      initialTime: TimeOfDay.fromDateTime(DateTime.now()),
    );
    if (time == null) return;

    setState(() {
      _preferredDateTime = DateTime(
        date.year,
        date.month,
        date.day,
        time.hour,
        time.minute,
      );
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Request Service'),
        bottom: PreferredSize(
          preferredSize: const Size.fromHeight(20.0),
          child: Padding(
            padding: const EdgeInsets.only(bottom: 8.0),
            child: Text(
              widget.handyman.name,
              style: const TextStyle(fontSize: 16, color: Colors.grey),
            ),
          ),
        ),
      ),
      body: BlocListener<BookingBloc, BookingState>(
        listener: (context, state) {
          if (state is BookingSuccess) {
            ScaffoldMessenger.of(context).showSnackBar(
              const SnackBar(content: Text('Request sent successfully!')),
            );
            context.pop();
          } else if (state is BookingError) {
            ScaffoldMessenger.of(
              context,
            ).showSnackBar(SnackBar(content: Text(state.message)));
          }
        },
        child: SingleChildScrollView(
          padding: const EdgeInsets.all(24.0),
          child: Form(
            key: _formKey,
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.stretch,
              children: [
                _buildTextField(
                  _issueController,
                  'Describe your issue *',
                  maxLines: 5,
                ),
                const SizedBox(height: 16),
                _buildDateTimeField(context),
                const SizedBox(height: 24),
                Container(
                  padding: const EdgeInsets.all(16.0),
                  decoration: BoxDecoration(
                    color: Colors.grey[200],
                    borderRadius: BorderRadius.circular(8.0),
                  ),
                  child: const Text(
                    'After your request is accepted, you\'ll be able to contact the handyman directly via WhatsApp, Telegram, or phone to discuss details and arrange the service.',
                    textAlign: TextAlign.center,
                    style: TextStyle(color: Colors.grey),
                  ),
                ),
                const SizedBox(height: 24),
                ElevatedButton(
                  onPressed: () {
                    if (_formKey.currentState!.validate()) {
                      final request = ServiceRequest(
                        requestId: '', // Will be generated by Firestore
                        customerId:
                            (context.read<AuthBloc>().state as Authenticated)
                                .user
                                .uid,
                        handymanId: widget.handyman.uid,
                        customerName:
                            (context.read<AuthBloc>().state as Authenticated)
                                .user
                                .displayName ??
                            '',
                        issueDescription: _issueController.text,
                        preferredTime: Timestamp.fromDate(_preferredDateTime!),
                        status: RequestStatus.pending,
                        createdAt: Timestamp.now(),
                      );
                      context.read<BookingBloc>().add(CreateBooking(request));
                    }
                  },
                  style: ElevatedButton.styleFrom(
                    backgroundColor: Colors.black,
                    foregroundColor: Colors.white,
                    padding: const EdgeInsets.symmetric(vertical: 16),
                  ),
                  child: const Text(
                    'Submit Request',
                    style: TextStyle(fontSize: 16),
                  ),
                ),
              ],
            ),
          ),
        ),
      ),
    );
  }

  Widget _buildTextField(
    TextEditingController controller,
    String label, {
    int maxLines = 1,
  }) {
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        Text(label, style: const TextStyle(fontWeight: FontWeight.bold)),
        const SizedBox(height: 8),
        TextFormField(
          controller: controller,
          maxLines: maxLines,
          decoration: InputDecoration(
            border: const OutlineInputBorder(),
            hintText: 'Please describe the problem or service you need...',
          ),
          validator: (value) {
            if (value == null || value.isEmpty) {
              return 'Please enter a description';
            }
            return null;
          },
        ),
      ],
    );
  }

  Widget _buildDateTimeField(BuildContext context) {
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        const Text(
          'Preferred Date & Time *',
          style: TextStyle(fontWeight: FontWeight.bold),
        ),
        const SizedBox(height: 8),
        TextFormField(
          readOnly: true,
          onTap: () => _selectDateTime(context),
          decoration: InputDecoration(
            border: const OutlineInputBorder(),
            hintText: _preferredDateTime == null
                ? 'mm/dd/yyyy --:--'
                : '${_preferredDateTime!.month}/${_preferredDateTime!.day}/${_preferredDateTime!.year} ${_preferredDateTime!.hour}:${_preferredDateTime!.minute}',
          ),
          validator: (value) {
            if (_preferredDateTime == null) {
              return 'Please select a date and time';
            }
            return null;
          },
        ),
      ],
    );
  }
}
